config/routes.rb
Katikia::Application.routes.draw do

  get '/home' => 'pages#home'
  get '/info' => 'pages#info'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :properties do
    collection do
      get :rent
      get :buy

      controller :favorites do
        get 'favorites' => :index
        post 'favorites' => :create
        delete 'favorites' => :destroy
        put 'favorites' => :update
      end

      controller :compares do
        get 'compare' => :index
        post 'compare' => :create
        delete 'compare' => :destroy
        put 'compare' => :update
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :properties do
        collection do
          get :rent
          get :buy
        end
      end
    end
  end

  root :to => 'pages#home'
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @property = Property.find(params[:id])
    if @property.favoritable_by?(current_user)
      current_user.favorites << @property
      redirect_to favorites_properties_path,
        notice: "You favorited #{ @property.category } at #{ @property.street }"
    else
      redirect_to :back, notice: "You can't favorite this property"
    end
  end

  def index
    @properties = current_user.favorites
  end

  def update
    @property = Property.find(params[:id])
    current_user.favorites.delete(@property)
    redirect_to :back,
      notice: "You unfavorited #{ @property.category } at #{ @property.street }"
  end

  def destroy
   current_user.favorites = []
   redirect_to :back
  end
end

app/views/favorites/index.html.erb
<%= title("Favorites") %>
<%= current_user.name %>
<div class="results row">
  <div class="span6">
    <h4> You have favorited the followings listings </h4>
  </div>
  <div class="reset-btn pull-right">
    <%= link_to "Clear favorites list", favorites_properties_path, class: "btn btn-small btn-danger", method: :delete %>
  </div>
</div>
<table class="table table-hover table-striped">
  <thead>
    <th> Image </th>
    <th> Description </th>
    <th> Address </th>
    <th> Price </th>
    <th> Days on Market </th>
  </head>
  <tbody>
  <% @properties.each do |property| %>
    <tr>
      <td><%= image_tag thumbnail(property, :small) %> </td>
      <td><%= property.title %></td>
      <td><%= property.street %> </td>
      <td><%= property.price %> </td>
      <td><%= (Date.today - property.created_at.to_date).to_i %>
      <td><%= link_to 'View', property_path(property) %></td>
      <td><%= link_to 'Remove from favorites',
                       favorites_properties_path(id: property),
                       method: 'put', confirm: 'Are you sure you want to remove this property from your favorites' %>
      </td>
      <td><%= link_to "Compare it", compare_properties_path(id: property), method: 'post' %></td>
    </tr>
<% end %>
  </tbody>
</table>