config/routes.rb
Katikia::Application.routes.draw do

  get '/home' => 'pages#home'
  get '/info' => 'pages#info'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :properties do
    collection do
      get :rent
      get :buy

      controller :favorites do
        get 'favorites' => :index
        post 'favorites' => :create
        delete 'favorites' => :destroy
        put 'favorites' => :update
      end

      controller :compares do
        get 'compare' => :index
        post 'compare' => :create
        delete 'compare' => :destroy
        put 'compare' => :update
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :properties do
        collection do
          get :rent
          get :buy
        end
      end
    end
  end

  root :to => 'pages#home'
end

app/models/property.rb
class Property < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :favorite_properties
  has_many :favorite_by, through: :favorite_properties, source: :user

  attr_accessible :floor_size, :price, :status, :street, :bedroom, :bathroom,
                  :parking, :street_number, :city, :summary, :year,
                  :images_attributes, :category

  accepts_nested_attributes_for :images, :allow_destroy => true,
                                reject_if: lambda {|a| [:attachment].blank? }

  validates :floor_size, :price, :status, :bedroom, :bathroom, :parking,
            :street, :street_number, :city, :year, :category, presence: true
  validates :floor_size, :bedroom, :bathroom, :parking, :street_number, numericality: true
  validates :year, numericality: { greater_than: 1900 }
  validates :summary, length: { maximum: 800 }

  geocoded_by :gmaps4rails_address
  after_validation :geocode

  acts_as_gmappable process_geocoding: false, check_process: false, validations: :false

  def gmaps4rails_address
    "#{self.street} #{self.street_number}, #{ self.city }, Greece"
  end

  scope :rent, where(status: "Rent")
  scope :buy, where(status: "Buy")

  index_name("#{Rails.env}-search-properties")

  def self.search(params)
    tire.search(load: true, page: params[:page], per_page: 12) do
      query do
        boolean do
          must { string params[:search][:query] } if params[:search][:query].present?

          must { string params[:search][:types].join(" ")
               } if params[:search][:types].present?

          price_from = params[:search][:price_from] if params[:search][:price_from].present?
          price_to = params[:search][:price_to] if params[:search][:price_to].present?
          must { range :price, { gte: price_from, lte: price_to }
               } if price_from || price_to

          bedrooms_from = params[:search][:bedrooms_from] if params[:search][:bedrooms_from].present?
          bedrooms_to = params[:search][:bedrooms_to] if params[:search][:bedrooms_to].present?
          must { range :bedroom, { gte: bedrooms_from, lte: bedrooms_to }
               } if bedrooms_from || bedrooms_to

          floor_size_from = params[:search][:floor_size_from] if params[:search][:floor_size_from].present?
          floor_size_to = params[:search][:floor_size_to] if params[:search][:floor_size_to].present?
          must { range :floor_size, { gte: floor_size_from, lte: floor_size_to }
               } if floor_size_from || floor_size_to
        end
      end

      sort { by :price, params[:sort] } if params[:sort].present?

    end
  end

  def title
    "#{ status } #{ category }"
  end

  def self.recently_created(size = 8)
    includes(:images).order("created_at ASC").limit(size)
  end

  def favoritable_by?(user)
    !(user.properties.include?(self) || user.favorites.include?(self))
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def new
    @property = Property.new
    @property.images.build
  end

  def create
    @property = current_user.properties.build(params[:property])
    if @property.save
      redirect_to @property
      flash[:success] = 'You have created a new property'
    else
      render :new
    end
  end

  def show
    @property = Property.find(params[:id])
    @json = @property.to_gmaps4rails
    @favs_quicklist = current_user.favorites.includes(:images).limit(4) if current_user
    @compares_quicklist = Property.includes(:images).find(session[:compare_list] || [])
  end

  def index
    @favs_quicklist = current_user.favorites.includes(:images).limit(4) if current_user
    @compares_quicklist = Property.includes(:images).find(session[:compare_list] || [])

    @properties = if params[:search].present?
                    Property.search(params)
                  elsif params[:sort].present?
                    Property.order('price ' + sort_order).includes(:images).page(params[:page]).per(18)
                  else
                    Property.includes(:images).page(params[:page]).per(18)
                  end

    @partial = if ['list', 'grid'].include?(params[:view])
                   cookies[:view ] = params[:view]
                 else
                   cookies[:view] || 'grid'
                 end
  end

  def rent
    @properties = Property.rent.page(params[:page]).per(12)
    @favs_quicklist = current_user.favorites.includes(:images).limit(4) if current_user
    @compares_quicklist = Property.includes(:images).find(session[:compare_list] || [])
    render :index
  end

  def buy
    @properties = Property.buy.page(params[:page]).per(12)
    @favs_quicklist = current_user.favorites.includes(:images).limit(4) if current_user
    @compares_quicklist = Property.includes(:images).find(session[:compare_list] || [])
    render :index
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(params[:property])
      redirect_to property_path
      flash[:success] = 'Property has been updated'
    else
      render :edit
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    flash[:success] = 'Property has been destroyed'
    redirect_to properties_path
  end

  private

  def correct_user
    redirect_to root_path if current_user.properties.find_by_id(params[:id]).nil?
  end

  def sort_order
    %w[asc desc].include?(params[:sort]) ? params[:sort] : "asc"
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def thumbnail(property, size)
    image = property.images.first
    image ? image.attachment.url(size) : Image.new.attachment.url
  end

  def property_search_results(properties)
    if properties.total_count > 0
      content_tag(:div, "Found #{ properties.total_count } property listings with this search criteria'",
                  class: 'alert alert-info alert-block')
    else
      content_tag(:div, "No property listings were found with this search criteria",
                  class: 'alert alert-block')
    end
  end

  def summary(property)
    if controller.action_name == "buy" || controller.action_name == "rent"
      property.category
    else
      property.title
    end
  end
end

app/views/properties/_compare_list.html.erb
<% unless session[:compare_list].nil? %>
  <div class="sidebar-widjet">
    <div class="accordion-toggle widjet-head" data-toggle="collapse" data-target="#comparisons" >
      <span>Compare List</span>
      <label class="badge badge-important ">
        <%= session[:compare_list].size %> of 3
      </label>
      <b class="caret-category"></b>
    </div>

    <div class="compare-list collapse in" id="comparisons">
      <div class="widjet-entries" id="compares">
        <ul class="stacked">
          <% properties.each do |property| %>
            <li>
          <%= link_to property_path(property) do %>
            <%= image_tag thumbnail(property, :small) %>
          <%= property.category %> <%= property.price %> $
          </li>
        <% end %>
        <% end %>
        </ul>
          <div id="compare-list-actions">
          <%= link_to "Show compare list", compare_properties_path,
                      class: "btn btn-small btn-info" %>
          <%= link_to "Clear list", compare_properties_path, method: "delete",
                      class: "btn btn-small btn-danger" %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/_favs.html.erb
<% if signed_in? %>
  <div class="sidebar-widjet">

    <div class="accordion-toggle widjet-head" data-toggle="collapse" data-target="#favs" >
      <span>Favorites List</span>
      <label class="badge badge-important ">
        <%= properties.size %> of <%= current_user.favorites.size %>
      </label>
      <b class="caret-category"></b>
    </div>

    <div class="favorite-list collapse in" id="favs" >
      <div class="widjet-entries" id="favorites">
        <ul class="stacked">
          <% properties.each do |property| %>
          <li>
          <%= link_to property_path(property) do %>
            <%= image_tag thumbnail(property, :small) %>
          <%= property.category %> <%= property.price %> $
          </li>
          <% end %>
        <% end %>
        </ul>

        <div id="compare-list-actions">
          <%= link_to "Show All Favorites", favorites_properties_path,
            class: "btn btn-small btn-info" %>
          <%= link_to "Clear list", favorites_properties_path, method: "delete",
            class: "btn btn-small btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/_form.html.erb
<%= simple_form_for(property, :html => { multipart: true,
                                          class: "form-horizontal" }) do |f| %>
  <%= f.error_notification message: "Something went wrong" %>
<div class="row leftpad">
  <div class="span4">
    <fieldset>
      <legend>Type</legend>
      <%= f.input :status, collection: ['Rent', 'Buy'] %>
      <%= f.input :category, collection: ['Apartment', 'Condo', 'Land',
                                          'Duplex', 'Triplex', 'House'] %>
      <%= f.input :price %>
    </fieldset>
  </div>
  <div class="span3 offset2">
    <fieldset>
      <legend>Address</legend>
      <%= f.input :city %>
      <%= f.input :street %>
      <%= f.input :street_number, label: "Number" %>
    </fieldset>
  </div>
</div>
<div class="row leftpad">
  <div class="span4">
    <fieldset>
      <legend>Features</legend>
      <%= f.input :floor_size %>
      <%= f.input :bedroom %>
      <%= f.input :bathroom %>
      <%= f.input :year %>
      <%= f.input :parking %>
    </fieldset>
  </div>
  <div class="span4 offset2">
    <fieldset>
      <legend>Summary</legend>
      <%= f.input :summary, input_html: { rows: "11" } %>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="span12">
    <fieldset class="pictures">
      <legend><h3>Pictures</h3></legend>
      <%= f.simple_fields_for :images do |img_form| %>
        <%= img_form.input :attachment, label: "Pictures" %>
        <%= img_form.hidden_field :attachment_cache %>
    <% end %>
    </fieldset>
  </div>
</div>
<hr class="small"></hr>
<div class="row">
  <div class="span4 offset4">
    <%= f.button :submit,
                  value: "#{ controller.action_name.camelcase } Property",
                  class: "btn-large btn-success" %>
    <% end %>
  </div>
</div>

app/views/properties/_grid.html.erb
<ul class="thumbnails">
  <% properties.each do |property| %>
  <li class="span3">
  <%= link_to property_path(property) do %>
    <div class="thumbnail listing-thumb">
      <%= image_tag thumbnail(property, :medium) %>

      <div class="price-tag">
        <%= property.price %> $
      </div>

      <div class="info">
        <div class="property-title">
          <%= summary(property) %>
        </div>

        <div class="rooms">
          <%= property.floor_size %> m² -
          <%= property.bedroom %> Rooms
        </div>

        <div class="location">
          <%= property.city %> <%= property.street %>
        </div>
      <% end %>
      </div>

    </div>
  </li>
<% end %>
</ul>

app/views/properties/_list.html.erb
<ul class="list thumbnails ">
  <% properties.each do |property| %>
  <li class="span9">
    <div class="properties-list">
      <%= link_to property_path(property) do %>
      <div class="properties-list-container">
        <%= image_tag thumbnail(property, :large) %>
      <% end %>

        <div class="price-tag">
          <%= property.price %> $
        </div>

        <div class="property-actions">
          <div class="more-info">
            <%= link_to "More info", property_path(property), class: "btn btn-medium" %>
          </div>
        </div>

        <div class="info">
          <div class="property-title">
            <%= summary(property) %>
          </div>

          <div class="rooms">
            <%= property.floor_size %> m² -
            <%= property.bedroom %> Rooms
          </div>

          <div class="location">
            <%= property.city %> <%= property.street %> <%= property.street_number %>
          </div>
        </div>

      </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/properties/_search_form.html.erb
<%= form_tag properties_path, method: :get, name: :search do %>

<div class="sidebar-widjet">
  <div class="widjet-head" id="search-query-head">
    <span>Your Search</span>
  </div>

  <div class="widjet-entries" id="search-query-entries">
    <%= text_field_tag "search[query]",
      (params[:search][:query] if params[:search]), placeholder: 'Rent Apartment Doiranis'%>
  <%= submit_tag "Quick Search", name: nil, class: "btn search-button" %>
  </div>
</div>

<%= property_search_results(properties) if params[:search].present? %>

<div class="sidebar-widjet">

  <div class="accordion-toggle widjet-head" data-toggle="collapse" href="#filter-results" id="search-filter-head">
    <span>Filter Your Results</span>
    <b class="caret-category"></b>
  </div>

  <div class="collapse in" id="filter-results">
    <div class="accordion-toggle widjet-head" data-toggle="collapse" href="#categories">
      <span>By category</span>
      <b class="caret-category"></b>
    </div>

    <div class="accordion-toggle categories-list collapse in" id="categories">
      <div class="widjet-entries">
        <ul>
      <% %w{ Apartment Condo Land Duplex Triplex House }.each do |type| %>
        <li>
          <label class="checkbox">
          <%= check_box_tag "search[types][]", type,
              (params[:search][:types].try(:include?,type) if params[:search]),
              id: type, class: "inline" %>
            <span><%= type %></span>
          </label>
        </li>
        <% end %>
      </ul>
      </div>
    </div>

    <div class="accordion-toggle widjet-head" data-toggle="collapse" href="#bedrooms">
      <span>By Bedrooms</span>
      <b class="caret-category"></b>
    </div>

    <div class="bedrooms-list collapse in" id="bedrooms">
      <div class="widjet-entries">
    <%= search_field_tag("search[bedrooms_from]",
                          (params[:search][:bedrooms_from] if params[:search]),
                          placeholder: 'from') %> -
    <%= search_field_tag("search[bedrooms_to]",
                          (params[:search][:bedrooms_to] if params[:search]),
                          placeholder: 'to') %>
      </div>
    </div>


    <div class="accordion-toggle widjet-head" data-toggle="collapse" href="#prices">
      <span>By Price</span>
      <b class="caret-category"></b>
    </div>

    <div class="price-list collapse in" id="prices">
      <div class="widjet-entries">
      <%= search_field_tag("search[price_from]",
                            (params[:search][:price_from] if params[:search]),
                            placeholder: 'from') %> -
      <%= search_field_tag("search[price_to]",
                            (params[:search][:price_to] if params[:search]),
                            placeholder: 'to') %>
      </div>
    </div>

    <div class="accordion-toggle widjet-head" data-toggle="collapse" href="#floor-sizes">
      <span>By floor size</span>
      <b class="caret-category"></b>
    </div>

    <div class="floor-size-list collapse in" id="floor-sizes">
      <div class="widjet-entries">
      <%= search_field_tag("search[floor_size_from]",
                            (params[:search][:floor_size_from] if params[:search]),
                            placeholder: 'from') %> -
      <%= search_field_tag("search[floor_size_to]",
                            (params[:search][:floor_size_to] if params[:search]),
                            placeholder: 'to') %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/properties/edit.html.erb
<%= title('Edit Property')%>
<div class="row">
  <div class="span12">
    <div id="form-property">
      <h3>Edit property</h3>
      <%= render 'form', property: @property %>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<%= title("Listings")%>

<div class="main row">

  <aside class="span3 search_form">
    <%= render 'search_form', properties: @properties %>
    <%= render 'compare_list', properties: @compares_quicklist %>
    <%= render 'favs', properties: @favs_quicklist %>
  </aside>

  <div class="span9">
    <div class="listings">

      <div class="results-panel">
        <div class="results">
            showing <%= @properties.count %> of <%= @properties.total_count %> results
        </div>

        <div class="results-options">
          <div class="btn-group">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <% if params[:sort] == 'asc' %>
                Price: Lowest First
              <% elsif params[:sort] == 'desc' %>
                Price: Highest First
              <% else %>
                Sort By
              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Price: Highest first', params.merge(sort: 'desc') %>
              <li><%= link_to 'Price: Lowest first', params.merge(sort: 'asc') %>
            </ul>
          </div>
        </div>

        <div class="viewer-toggle-nav results-options">
          <ul>
          <span>View as:</span>
            <li><%= link_to_unless params[:view] == 'grid' || cookies[:view] == 'grid' || cookies[:view].blank?,
              "<i class=icon-th icon-3x></i> Thumbnails".html_safe, params.merge(view: 'grid') %></li>
            <li><%= link_to_unless params[:view] == 'list' || cookies[:view] == 'list',
              "<i class=icon-list icon-3x></i> List".html_safe, params.merge(view: 'list') %></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="span9">
          <section>
            <%= render @partial, properties: @properties %>
          </section>
        </div>
      </div>

      <div class="pagination-panel">
        <div class="results">
          Showing <%= @properties.count %> of <%= @properties.total_count %> results
        </div>
        <%= paginate @properties %>
      </div>

    </div>
  </div>
</div>

app/views/properties/new.html.erb
<%= title('New property') %>
<div class="row">
  <div class="span12">
    <div id="form-property">
      <h3>Create a property</h3>
      <%= render 'form', property: @property %>
    </div>
  </div>
</div>

app/views/properties/show.html.erb
<%= title(@property.category)%>
<div class="row">
  <div class="span9">
    <div class="listing">
      <div class="row">
        <div class="span8">
          <article>
            <header>
              <h3><%= @property.title %> at
                  <%= @property.street %> <small><%= @property.floor_size %> m²</small>
                  <span id="price" class="label label-success">
                  <%= @property.price %> $
                  </span>
              </h3>
            </header>
            <hr class="small"></hr>
            <div class="property-images">
              <% @property.images.each do |image| %>
                <%= image_tag image.attachment.normal.url, class: "img-polaroid" %>
              <% end %>
            </div>
            <hr class="small"></hr>
            <ul class="nav nav-tabs">
              <li class="active"> <a href="#description" data-toggle="tab">Description</a> </li>
              <li class="inactive" id="googlemap"><a href="#gmap" data-toggle="tab">Map</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="description">
                <div class="row">
                  <div class="span8">
                    <h3>Summary</h3>
                      <p>
                        <%= @property.summary %></br>
                      </p>
                    <h3> Key Features </h3>
                    <div class="row">
                      <div class="span3">
                        <ul class="unstyled">
                          <li><i class="icon-ok"></i>
                          Category: <%= @property.category %>
                          </li>
                          <li><i class="icon-ok"></i>
                          Bathrooms: <%= @property.price %>
                          </li>
                          <li><i class="icon-ok"></i>
                          Floor Size: <%= @property.floor_size %> m²
                          </li>
                        </ul>
                      </div>

                      <div class="span3">
                        <ul class="unstyled">
                          <li><i class="icon-ok"></i>
                          Bedrooms: <%= @property.bedroom %>
                          </li>
                          <li><i class="icon-ok"></i>
                          Bathrooms: <%= @property.bathroom %>
                          </li>
                          <li><i class="icon-ok"></i>
                          Parking: <%= @property.parking %>
                          </li>
                        </ul>
                      </div>
                      <div class="span2">
                        <ul class="unstyled">
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="gmap">
                <div class="row">
                  <div class="span8">
                    <%= gmaps({
                      "map_options" => { "auto_zoom" => false, "zoom" => 18,
                                         "auto_adjust" => true },
                      "markers"     => { "data" => @json }}) %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr class="small"></hr>
        <div class="row">
          <div class="span9">
            <h3> Similar Properties</h3>
          </div>
        </div>
      </div>
    </div>
  </article>

  <!-- admin action -->
  <div class="span3">
    <div class="row">
      <% if current_user?(@property.user) %>
        <div class="span3">
          <div id="admin-box">
            <ul class="nav nav-tabs nav-stacked">
              <li class="active"><a href="#">Admin</a><li>
              <li><%= link_to '<i class=icon-edit></i> Edit Property'.html_safe,
                      edit_property_path, class: "" %>
              </li>
              <li><%= link_to '<i class=icon-trash></i> Delete Property'.html_safe,
                      property_path, method: :delete,
                      confirm: 'Are you sure you want to delete this property' %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>

    <!-- property actions -->
    <div class="row">
      <div class="span3">
        <div id="actions-box">
          <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">Actions</a></li>

            <li><%= link_to_if !current_user || @property.favoritable_by?(current_user),
              "<i class=icon-star></i> Marks as favorite".html_safe,
              favorites_properties_path(id: @property),
              method: "post" %></li>

            <li><%= link_to_if current_user && current_user.favorites.include?(@property),
              "<i class=icon-star-empty></i> Remove from favorites".html_safe,
                favorites_properties_path(id: @property),
                method: "put" %></li>

            <li><%= link_to "<i class=icon-search></i> View similar properties".html_safe, '#' %></li>
            <li><%= link_to "<i class=icon-tasks></i> Compare it".html_safe, compare_properties_path(id: @property.id), method: "post" %></li>
            <li><a href="#" onclick="window.print(); return false;"><i class=icon-print></i> Print Listing</a></li>
            <li><%= link_to "<i class=icon-envelope></i> Email this listing".html_safe, '#' %></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- favorites properties -->
    <div class = "row">
      <div class="span3">
        <%= render 'favs', properties: @favs_quicklist %>
      </div>
    </div>
    <div class = "row">
      <div class="span3">
        <%= render 'compare_list', properties: @compares_quicklist %>
      </div>
    </div>
  </div>
</div>