config/routes.rb
Katikia::Application.routes.draw do

  get '/home' => 'pages#home'
  get '/info' => 'pages#info'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :properties do
    collection do
      get :rent
      get :buy

      controller :favorites do
        get 'favorites' => :index
        post 'favorites' => :create
        delete 'favorites' => :destroy
        put 'favorites' => :update
      end

      controller :compares do
        get 'compare' => :index
        post 'compare' => :create
        delete 'compare' => :destroy
        put 'compare' => :update
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :properties do
        collection do
          get :rent
          get :buy
        end
      end
    end
  end

  root :to => 'pages#home'
end

app/views/pages/about.html.erb
<%= title("About") %>

<h1>About Real Estate</h1>
<p> A real estate application build with ruby on rails </p>

app/views/pages/home.html.erb
<%= title("Home") %>
<%= description("Rent, Buy properties in Greece") %>

<div class="landing-page-search">
  <%= form_tag properties_path, method: :get, name: :search do %>
    <%= text_field_tag "search[query]",
      (params[:search][:query] if params[:search]), autofocus: true,
      placeholder: 'Rent Apartment Doiranis'%>
    <%= submit_tag "Quick Search", name: nil, class: "btn search-button" %>
  <% end %>
</div>

<hr></hr>

<div class="row">

  <div class="span3">
    <div class="sidebar-widjet" id="landing-page-sidebar">
      <div class="widjet-head" id="search-query-head">
        <span>Browse By City</span>
      </div>

      <div class="widjet-entries" id="search-query-entries">
      </div>
    </div>

    <div class="sidebar-widjet">
      <div class="widjet-head" id="search-query-head">
        <span>Browse By Category</span>
      </div>

      <div class="widjet-entries" id="search-query-entries">
      </div>
    </div>
  </div>

  <% unless @properties.empty? %>
    <div class="featured-properties listings span9">
    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">

        <div class="item active">
          <%= link_to property_path(@properties.first) do %>
            <%= image_tag thumbnail(@properties.first, :featured) %>
          <div class="carousel-caption">
            <h4>
              <%= @properties.first.title %>
            </h4>
            <p>
            <%= @properties.first.city %> <%= @properties.first.street %>
            </p>
            <p class="featured-price-tag">
            <%= @properties.first.price %> $
            </p>
          </div>
        <% end %>
        </div>

        <% @properties.last(2).each do |property| %>
          <div class="item">
          <%= link_to property_path(property) do %>
            <%= image_tag thumbnail(property, :featured) %>
          <div class="carousel-caption">
            <h4>
              <%= property.title %>
            </h4>
            <p>
            <%= property.city %>  <%= property.street %>
            </p>
            <p class="featured-price-tag">
            <%= property.price %> $
            </p>
          </div>
        <% end %>
        </div>
      <% end %>
      </div>

      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
  </div>
<% end %>
</div>

<div class="row">
  <div class="span12 listings">
    <div class="latest_properties">
      <h2> Latest properties </h2>
    </div>
    <%= render 'properties/grid', properties: @properties %>
  </div>
</div>

<hr class="small"></hr>
<div class="landing-page-info">
  <div class="row">
    <div class="span12">
      <ul class="thumbnails">

        <li class="span4">
        <%= link_to properties_path do %>
          <div class="thumbnail thumbnail-info" id="nearby-properties">
          <div class="caption"> Find nearby places</div>
        </div>
      <% end %>
        </li>

        <li class="span4">
        <%= link_to new_property_path do %>
          <div class="thumbnail thumbnail-info" id="list-place">
          <div class="caption"> List a property for free </div>
        </div>
      <% end %>
        </li>

        <li class="span4">
        <%= link_to do %>
          <div class="thumbnail thumbnail-info" id="agent-info">
          <div class="caption"> Register as an agent </div>
        </div>
      <% end %>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/pages/info.html.erb
<%= title("Info") %>

<h1>About Real Estate</h1>
<p> A real estate application build with ruby on rails </p>