config/routes.rb
Katikia::Application.routes.draw do

  get '/home' => 'pages#home'
  get '/info' => 'pages#info'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :properties do
    collection do
      get :rent
      get :buy

      controller :favorites do
        get 'favorites' => :index
        post 'favorites' => :create
        delete 'favorites' => :destroy
        put 'favorites' => :update
      end

      controller :compares do
        get 'compare' => :index
        post 'compare' => :create
        delete 'compare' => :destroy
        put 'compare' => :update
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :properties do
        collection do
          get :rent
          get :buy
        end
      end
    end
  end

  root :to => 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="top-footer">
          <!-- Copyright info and links -->
          <div class="row">
            <div class="span3">
              <h4>Faq</h4>
              <ul class="unstyled">
                <li><%= link_to 'Buying a Property', '#' %></li>
                <li><%= link_to 'Renting a Property', '#' %></li>
                <li><%= link_to 'Selling a Property', '#' %></li>
              </ul>
            </div>

            <div class="span3">
              <h4>About Us</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Nullam a nisi mi, et posuere eros. Vivamus et risus
            </div>

            <div class="span3" id="contact">
              <h4>Contact</h4>
              <ul>

                <li><i class="icon-twitter "></i>
                <%= link_to 'Twitter', 'http://twitter.com/georgebellos' %>
                </li>

                <li><i class="icon-envelope"></i>
                <%= link_to 'realestate@georgebellos.com', '#' %>
                </li>

                <li> <i class="icon-user"></i> Tel. 111-222-3333 </li>

                <li><i class="icon-map-marker"></i> 31 Somewhere Street Greece </li>

                <li> <i class="icon-time"></i> Office Hours: 8am - 6pm</li>

              </ul>
            </div>

            <div class="span3">
              <h4>Latest News</h4>
              <ul>
                <li><%= link_to 'Lorem ipsum dolor sit amet ultricies aliquam purus', '#' %></li>
                <li><%= link_to 'Consectetur adipiscing elit. Nullam', '#' %></li>
                <li><%= link_to 'Quisque quis tellus et augue feugiat semper at nec libero', '#' %></li>
              </ul>
            </div>

            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="footer-bottom">
    <center id="copyright">
      Real Estate Greece 2012 | Created by <a href="http://georgebellos.com">George Bellos</a>
    </center>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-static-top' id="topbar">
  <div class='navbar-inner'>
    <div class='container'>
      <%= link_to "Katikia", root_path, class: "brand", id: "logo" %>
      <nav>
        <ul class='nav'>
          <li><%= link_to "Properties", properties_path %>
          <li><%= link_to "To Rent", rent_properties_path %>
          <li><%= link_to "For Sale", buy_properties_path %>
        <li><%= link_to "List a Property", new_property_path %>
      </ul>
        <ul class='nav pull-right'>
          <% if user_signed_in? %>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method=>'delete' %>
            <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %> </li>
            <li class="divider-vertical"></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield_or_default :title, "Real Estate" %></title>
    <meta name="description" content="<%= yield_or_default :description, "Real Estate Greece" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrap">
      <%= render "layouts/header" %>
      <div class="container">
        <div class="content">
          <div class="row">
            <div class="span12">
              <%= render "shared/flash_messages", flash: flash %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="push"></div>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>
  </body>
</html>